import { describe, test, expect } from "bun:test";
import { impliesList, generateProfile } from "../src/learn/generate";
import type { McpTool } from "../src/learn/client";

// ── impliesList ───────────────────────────────────────────────────────────────

describe("impliesList", () => {
  test("list_ prefix implies list", () => {
    expect(impliesList("list_issues")).toBe(true);
    expect(impliesList("mcp__jira__list_issues")).toBe(true);
  });

  test("search_ prefix implies list", () => {
    expect(impliesList("search_pages")).toBe(true);
  });

  test("find_ prefix implies list", () => {
    expect(impliesList("find_users")).toBe(true);
  });

  test("get_ prefix does not imply list", () => {
    expect(impliesList("get_issue")).toBe(false);
  });

  test("create_ prefix does not imply list", () => {
    expect(impliesList("create_issue")).toBe(false);
  });

  test("delete_ prefix does not imply list", () => {
    expect(impliesList("delete_issue")).toBe(false);
  });

  test("uses description fallback for ambiguous names", () => {
    expect(impliesList("execute", "Returns a list of results")).toBe(true);
    expect(impliesList("execute", "Runs a command")).toBe(false);
  });
});

// ── generateProfile ───────────────────────────────────────────────────────────

describe("generateProfile", () => {
  const listTools: McpTool[] = [
    { name: "list_issues", description: "List Jira issues" },
    { name: "search_issues", description: "Search issues" },
    { name: "get_issue", description: "Get a single issue" },
    { name: "create_issue", description: "Create a new issue" },
  ];

  const writeOnlyTools: McpTool[] = [
    { name: "create_record", description: "Create a record" },
    { name: "update_record", description: "Update a record" },
    { name: "delete_record", description: "Delete a record" },
  ];

  test("generates json_extract when list tools detected", () => {
    const toml = generateProfile("jira", listTools);
    expect(toml).toContain('type = "json_extract"');
    expect(toml).toContain("items_path");
    expect(toml).toContain("fields");
  });

  test("generates json_truncate when no list tools detected", () => {
    const toml = generateProfile("myservice", writeOnlyTools);
    expect(toml).toContain("json_truncate");
    expect(toml).not.toContain("items_path");
  });

  test("profile id uses server key with underscores", () => {
    const toml = generateProfile("my-jira", listTools);
    expect(toml).toContain('id          = "mcp__my_jira"');
    expect(toml).toContain('mcp_pattern = "mcp__my_jira__*"');
  });

  test("profile id normalizes hyphens", () => {
    const toml = generateProfile("some-service", writeOnlyTools);
    expect(toml).toContain('"mcp__some_service"');
  });

  test("includes generator comment", () => {
    const toml = generateProfile("jira", listTools);
    expect(toml).toContain("# Generated by: mcp-recall learn");
  });

  test("includes detected list tools in comment", () => {
    const toml = generateProfile("jira", listTools);
    expect(toml).toContain("list_issues");
    expect(toml).toContain("search_issues");
  });

  test("includes common fields in json_extract", () => {
    const toml = generateProfile("jira", listTools);
    expect(toml).toContain('"id"');
    expect(toml).toContain('"title"');
    expect(toml).toContain('"status"');
  });

  test("suggests issue-related items_path for jira", () => {
    const toml = generateProfile("jira", listTools);
    expect(toml).toContain('"issues"');
  });

  test("generated TOML is parseable", async () => {
    const { parse } = await import("smol-toml");
    const toml = generateProfile("jira", listTools);
    expect(() => parse(toml)).not.toThrow();
  });

  test("generated json_truncate TOML is parseable", async () => {
    const { parse } = await import("smol-toml");
    const toml = generateProfile("myservice", writeOnlyTools);
    expect(() => parse(toml)).not.toThrow();
  });

  test("handles empty tool list gracefully", () => {
    const toml = generateProfile("empty", []);
    expect(toml).toContain("json_truncate"); // no list tools → truncate
    expect(typeof toml).toBe("string");
  });
});
