/**
 * Generates a TOML profile string from a set of MCP tool schemas.
 *
 * Strategy selection heuristic:
 *   - If any tool name implies a list result (list/search/find/query/all) → json_extract
 *   - Otherwise → json_truncate
 *
 * Field suggestions for json_extract are derived from inputSchema property
 * names (as a proxy when output schema is unavailable), supplemented by
 * universal common fields. Users should refine these after running the tool.
 */
import type { McpTool } from "./client";

const LIST_VERBS = /^(list|search|find|query|get_all|fetch_all)/i;
const SINGLE_VERBS = /^(get|fetch|read|describe|show|retrieve)/i;
const WRITE_VERBS = /^(create|update|delete|remove|set|add|post|put|patch)/i;

const COMMON_FIELDS = ["id", "title", "name", "status", "description"];

/** Returns true if the tool likely returns a collection. */
export function impliesList(toolName: string, description?: string): boolean {
  const base = toolName.split("__").pop() ?? toolName;
  if (LIST_VERBS.test(base)) return true;
  if (WRITE_VERBS.test(base)) return false;
  if (SINGLE_VERBS.test(base)) return false;
  // Fall back to description heuristic
  if (description) {
    const d = description.toLowerCase();
    return d.includes("list") || d.includes("search") || d.includes("results");
  }
  return false;
}

/** Extracts candidate field names from a JSON Schema object. */
function schemaFields(inputSchema: Record<string, unknown> | undefined): string[] {
  if (!inputSchema) return [];
  const props = inputSchema["properties"] as Record<string, unknown> | undefined;
  if (!props) return [];
  // Only include string/number scalar properties that look like output fields
  return Object.keys(props).filter((k) => !["limit", "cursor", "offset", "page", "query", "filter"].includes(k));
}

/**
 * Suggests items_path values based on common naming patterns across tool
 * names in the server. E.g. tools referencing "issue" → try "issues" first.
 */
function suggestItemsPaths(serverKey: string, tools: McpTool[]): string[] {
  const allNames = tools.map((t) => t.name.toLowerCase()).join(" ");
  const paths: string[] = [];

  const keywords: Array<[string, string]> = [
    ["issue", "issues"],
    ["ticket", "tickets"],
    ["page", "pages"],
    ["item", "items"],
    ["result", "results"],
    ["task", "tasks"],
    ["record", "records"],
    ["node", "nodes"],
    ["message", "messages"],
  ];

  for (const [keyword, path] of keywords) {
    if (allNames.includes(keyword) || serverKey.includes(keyword)) paths.push(path);
  }

  // Always append universal fallbacks
  for (const fb of ["items", "results", "data", "nodes"]) {
    if (!paths.includes(fb)) paths.push(fb);
  }

  return paths.slice(0, 6); // keep it readable
}

/** Builds the complete TOML string for a generated profile. */
export function generateProfile(serverKey: string, tools: McpTool[]): string {
  const id = `mcp__${serverKey.replace(/-/g, "_")}`;
  const pattern = `mcp__${serverKey.replace(/-/g, "_")}__*`;
  const toolCount = tools.length;
  const listTools = tools.filter((t) => impliesList(t.name, t.description));
  const useExtract = listTools.length > 0;

  const description = `Auto-generated profile for ${serverKey} (${toolCount} tool${toolCount === 1 ? "" : "s"} — run mcp-recall learn to regenerate)`;

  if (!useExtract) {
    return [
      `# Generated by: mcp-recall learn`,
      `# Tools: ${tools.map((t) => t.name.split("__").pop()).join(", ")}`,
      `# Refine strategy.fields after observing real tool output.`,
      ``,
      `[profile]`,
      `id          = "${id}"`,
      `version     = "1.0.0"`,
      `description = "${description}"`,
      `mcp_pattern = "${pattern}"`,
      ``,
      `[strategy]`,
      `type            = "json_truncate"`,
      `max_depth       = 3`,
      `max_array_items = 5`,
      `fallback_chars  = 500`,
    ].join("\n") + "\n";
  }

  // Gather candidate fields: from input schemas of list tools + common fields
  const schemaHints = listTools.flatMap((t) => schemaFields(t.inputSchema));
  const candidateFields = [...new Set([...COMMON_FIELDS, ...schemaHints])].slice(0, 8);
  const itemsPaths = suggestItemsPaths(serverKey, tools);

  const fieldsToml = candidateFields.map((f) => `  "${f}",`).join("\n");
  const pathsToml = itemsPaths.map((p) => `  "${p}",`).join("\n");

  return [
    `# Generated by: mcp-recall learn`,
    `# List tools detected: ${listTools.map((t) => t.name.split("__").pop()).join(", ")}`,
    `# Refine items_path and fields after observing real tool output.`,
    ``,
    `[profile]`,
    `id          = "${id}"`,
    `version     = "1.0.0"`,
    `description = "${description}"`,
    `mcp_pattern = "${pattern}"`,
    ``,
    `[strategy]`,
    `type = "json_extract"`,
    `items_path = [`,
    pathsToml,
    `]`,
    `fields = [`,
    fieldsToml,
    `]`,
    `max_items           = 10`,
    `max_chars_per_field = 200`,
    `fallback_chars      = 500`,
  ].join("\n") + "\n";
}
